name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
    - name: Login in docker
      run: docker login -u=${{ secrets.DOCKER_HUB_LOGIN }} -p=${{ secrets.DOCKER_HUB_PASSWORD }}
      
    - name: Push to docker hub
      run: docker push $IMAGE_NAME
